name: pikachu_workout
description: Pikachu Workout - powerful home workout app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.0
  video_player: ^2.9.5
  flutter_svg: ^2.0.17
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/banners/
