import 'dart:async';
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:video_player/video_player.dart';

const orange = Color(0xFFFF7A00);
const dark = Color(0xFF101114);
const supabaseUrl = String.fromEnvironment('SUPABASE_URL');
const supabaseAnonKey = String.fromEnvironment('SUPABASE_ANON_KEY');

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  if (supabaseUrl.isNotEmpty && supabaseAnonKey.isNotEmpty) {
    await Supabase.initialize(url: supabaseUrl, anonKey: supabaseAnonKey);
  }
  runApp(const PikachuWorkout());
}

class PikachuWorkout extends StatelessWidget {
  const PikachuWorkout({super.key});
  @override Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false, title: 'Pikachu Workout', theme: ThemeData(useMaterial3: true, colorSchemeSeed: orange, scaffoldBackgroundColor: const Color(0xFFF7F7F7)),
    home: const HomeShell(),
  );
}

class Exercise { final String name; final int seconds; final int reps; final String muscle; final IconData icon; final String? video;
  const Exercise(this.name,this.seconds,this.reps,this.muscle,this.icon,[this.video]); }
final exercises = <Exercise>[
  Exercise('Jumping Jacks',20,0,'Full Body',Icons.accessibility_new), Exercise('Abdominal Crunches',0,16,'Abs',Icons.self_improvement),
  Exercise('Russian Twist',0,20,'Abs',Icons.rotate_left), Exercise('Mountain Climbers',30,0,'Core',Icons.directions_run),
  Exercise('Push Ups',0,12,'Chest',Icons.fitness_center), Exercise('Bodyweight Squats',30,0,'Legs',Icons.airline_seat_legroom_normal),
  Exercise('Lunges',24,0,'Legs & Glutes',Icons.directions_walk), Exercise('Plank',30,0,'Core',Icons.horizontal_rule),
  Exercise('High Knees',30,0,'Cardio',Icons.directions_run), Exercise('Glute Bridge',20,0,'Glutes',Icons.accessibility),
  Exercise('Triceps Dips',0,12,'Arms',Icons.chair), Exercise('Arm Circles',20,0,'Shoulders',Icons.sync),
];

class HomeShell extends StatefulWidget { const HomeShell({super.key}); @override State<HomeShell> createState()=>_HomeShellState(); }
class _HomeShellState extends State<HomeShell> { int tab=0;
  @override Widget build(BuildContext c){ final pages=[const Dashboard(),const Workouts(),const Profile()]; return Scaffold(body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.fitness_center_outlined),selectedIcon:Icon(Icons.fitness_center),label:'Workouts'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Profile')])); }
}

class Dashboard extends StatelessWidget { const Dashboard({super.key});
  @override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[
    Row(children:[const CircleAvatar(radius:25,backgroundColor:orange,child:Text('P',style:TextStyle(fontWeight:FontWeight.w900,fontSize:26,color:Colors.white))),const SizedBox(width:12),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Good morning 👋',style:TextStyle(color:Colors.grey)),Text('Pikachu Athlete',style:TextStyle(fontSize:22,fontWeight:FontWeight.w800))])),IconButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const SettingsPage())),icon:const Icon(Icons.settings_outlined))]),
    const SizedBox(height:18), Container(height:190,padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:dark,borderRadius:BorderRadius.circular(28)),child:Stack(children:[const Positioned(right:0,top:0,child:Icon(Icons.bolt,size:90,color:orange)),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('BE HEALTHY',style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),const Text('BE STRONGER',style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),const Text('BE YOURSELF',style:TextStyle(color:orange,fontSize:28,fontWeight:FontWeight.w900)),const Spacer(),FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const WorkoutDetail(title:'Full Body Workout'))),child:const Text('START WORKOUT  →'))])]),
    const SizedBox(height:20), Row(children:[_stat('🔥','7','Day streak'),_stat('⚡','420','Kcal'),_stat('⏱','35','Min')]), const SizedBox(height:24), const Text('Today’s Workout',style:TextStyle(fontSize:22,fontWeight:FontWeight.w800)),const SizedBox(height:12),
    _workCard(c,'Full Body Workout','35 min • 12 exercises','🔥 420 kcal'), const SizedBox(height:22),const Text('Quick Start',style:TextStyle(fontSize:22,fontWeight:FontWeight.w800)),const SizedBox(height:12),Wrap(spacing:10,runSpacing:10,children:['Abs','Chest','Legs','Arms','HIIT'].map((x)=>ActionChip(label:Text(x),onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>WorkoutDetail(title:'$x Workout'))))).toList())
  ]));
}
Widget _stat(String a,String b,String d)=>Expanded(child:Container(margin:const EdgeInsets.only(right:8),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:Column(children:[Text(a,style:const TextStyle(fontSize:20)),Text(b,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),Text(d,style:const TextStyle(color:Colors.grey,fontSize:12))])));
Widget _workCard(BuildContext c,String title,String sub,String kcal)=>Card(elevation:0,shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(22)),child:ListTile(contentPadding:const EdgeInsets.all(14),leading:Container(width:60,height:60,decoration:BoxDecoration(color:orange.withOpacity(.12),borderRadius:BorderRadius.circular(16)),child:const Icon(Icons.fitness_center,color:orange,size:30)),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('$sub\n$kcal'),trailing:const Icon(Icons.arrow_forward_ios,size:16),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>WorkoutDetail(title:title))));

class Workouts extends StatelessWidget { const Workouts({super.key}); @override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[const Text('Workouts',style:TextStyle(fontSize:32,fontWeight:FontWeight.w900)),const SizedBox(height:6),const Text('Train anywhere. No gym required.',style:TextStyle(color:Colors.grey)),const SizedBox(height:18),...['Full Body','Abs Beginner','Legs & Glutes','Chest & Arms','HIIT Cardio','Mobility & Stretch'].map((x)=>_workCard(c,x,x=='Abs Beginner'?'16 min • 16 exercises':'30 min • 12 exercises','🔥 ${x=='HIIT Cardio'?'350':'280'} kcal'))])); }

class WorkoutDetail extends StatelessWidget { final String title; const WorkoutDetail({super.key,required this.title}); @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(title)),body:Column(children:[Container(width:double.infinity,height:170,margin:const EdgeInsets.all(14),padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:dark,borderRadius:BorderRadius.circular(28)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('LEVEL 1',style:TextStyle(color:orange,fontWeight:FontWeight.w900,fontSize:28)),Spacer(),Text('30 Minutes • 12 Exercises',style:TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w700))])),Expanded(child:ListView.builder(itemCount:exercises.length,itemBuilder:(c,i){final e=exercises[i];return ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:18,vertical:7),leading:ExercisePreview(exercise:e,size:74),title:Text(e.name,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(e.seconds>0?'⏱ 00:${e.seconds.toString().padLeft(2,'0')}':'× ${e.reps}'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ExercisePage(exercise:e)));})),SafeArea(child:Padding(padding:const EdgeInsets.all(14),child:SizedBox(width:double.infinity,height:56,child:FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>WorkoutPlayer(list:exercises))),child:const Text('GO!',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900))))))])); }

class ExercisePreview extends StatefulWidget { final Exercise exercise; final double size; const ExercisePreview({super.key,required this.exercise,required this.size}); @override State<ExercisePreview> createState()=>_ExercisePreviewState(); }
class _ExercisePreviewState extends State<ExercisePreview> with SingleTickerProviderStateMixin { late AnimationController a; @override void initState(){super.initState();a=AnimationController(vsync:this,duration:const Duration(milliseconds:900))..repeat(reverse:true);} @override void dispose(){a.dispose();super.dispose();} @override Widget build(BuildContext c)=>AnimatedBuilder(animation:a,builder:(_,__)=>Container(width:widget.size,height:widget.size,decoration:BoxDecoration(color:dark,borderRadius:BorderRadius.circular(18)),child:Transform.translate(offset:Offset(0,-4*a.value),child:Icon(widget.exercise.icon,color:orange,size:widget.size*.5)))); }

class ExercisePage extends StatelessWidget { final Exercise exercise; const ExercisePage({super.key,required this.exercise}); @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(exercise.name.toUpperCase())),body:ListView(children:[Container(color:const Color(0xFF0A9F93),padding:const EdgeInsets.fromLTRB(16,0,16,25),child:DefaultTabController(length:2,child:Column(children:[const TabBar(tabs:[Tab(text:'ANIMATION'),Tab(text:'VIDEO')],labelColor:Colors.white,unselectedLabelColor:Colors.white70),SizedBox(height:360,child:TabBarView(children:[Center(child:ExerciseAnimation(exercise:exercise)),VideoPanel(url:exercise.video)]))]))),_info('Introduction','Perform ${exercise.name} with controlled movement. Keep your core engaged, breathe steadily, and use a comfortable range of motion. Stop if you feel sharp pain.'),_info('Muscle Focus',exercise.muscle),Padding(padding:const EdgeInsets.all(16),child:FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>WorkoutPlayer(list:[exercise]))),child:const Text('START EXERCISE')))])); }
Widget _info(String h,String t)=>Container(margin:const EdgeInsets.fromLTRB(10,10,10,0),padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(12),boxShadow:[BoxShadow(color:Colors.black.withOpacity(.06),blurRadius:5)]),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(h,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w700)),const SizedBox(height:12),Text(t,style:const TextStyle(fontSize:17,color:Colors.grey,height:1.35))]));
}

class ExerciseAnimation extends StatefulWidget { final Exercise exercise; const ExerciseAnimation({super.key,required this.exercise}); @override State<ExerciseAnimation> createState()=>_ExerciseAnimationState(); }
class _ExerciseAnimationState extends State<ExerciseAnimation> with SingleTickerProviderStateMixin {late AnimationController c;@override void initState(){super.initState();c=AnimationController(vsync:this,duration:const Duration(milliseconds:800))..repeat(reverse:true);}@override void dispose(){c.dispose();super.dispose();}@override Widget build(BuildContext x)=>AnimatedBuilder(animation:c,builder:(_,__)=>Container(width:300,height:300,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(30)),child:CustomPaint(painter:WorkoutPainter(c.value,widget.exercise.name))));}
class WorkoutPainter extends CustomPainter {final double t;final String name;WorkoutPainter(this.t,this.name);@override void paint(Canvas p,Size s){final q=Paint()..strokeWidth=12..strokeCap=StrokeCap.round..style=PaintingStyle.stroke..color=dark;final f=Paint()..color=orange;final cx=s.width/2, y=95+(name.contains('Squat')?t*30:0);p.drawCircle(Offset(cx,y),25,f);p.drawLine(Offset(cx,y+28),Offset(cx,y+115),q);final spread=name.contains('Jack')?35+70*t:25;p.drawLine(Offset(cx,y+45),Offset(cx-spread,y+75),q);p.drawLine(Offset(cx,y+45),Offset(cx+spread,y+75),q);p.drawLine(Offset(cx,y+115),Offset(cx-45,y+190),q);p.drawLine(Offset(cx,y+115),Offset(cx+45,y+190),q);p.drawCircle(Offset(cx,y+40),10,f);} @override bool shouldRepaint(c)=>true;}

class VideoPanel extends StatefulWidget {final String? url;const VideoPanel({super.key,this.url});@override State<VideoPanel> createState()=>_VideoPanelState();}
class _VideoPanelState extends State<VideoPanel>{VideoPlayerController? v;@override void initState(){super.initState();if(widget.url!=null&&widget.url!.isNotEmpty){v=VideoPlayerController.networkUrl(Uri.parse(widget.url!))..initialize().then((_){setState((){});});}}@override void dispose(){v?.dispose();super.dispose();}@override Widget build(BuildContext c){if(v==null)return const Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.video_library_outlined,size:60,color:orange),SizedBox(height:10),Text('Exercise video will appear here',style:TextStyle(color:Colors.grey))]);if(!v!.value.isInitialized)return const Center(child:CircularProgressIndicator());return Stack(alignment:Alignment.center,children:[AspectRatio(aspectRatio:v!.value.aspectRatio,child:VideoPlayer(v!)),IconButton.filled(onPressed:()=>setState(()=>v!.value.isPlaying?v!.pause():v!.play()),icon:Icon(v!.value.isPlaying?Icons.pause:Icons.play_arrow))]);}}

class WorkoutPlayer extends StatefulWidget {final List<Exercise> list;const WorkoutPlayer({super.key,required this.list});@override State<WorkoutPlayer> createState()=>_WorkoutPlayerState();}
class _WorkoutPlayerState extends State<WorkoutPlayer>{int i=0,left=20;Timer? timer;bool running=false;@override void initState(){super.initState();start();}void start(){timer?.cancel();running=true;left=widget.list[i].seconds>0?widget.list[i].seconds:30;timer=Timer.periodic(const Duration(seconds:1),(_){if(!mounted)return;if(left<=1){if(i<widget.list.length-1){setState(()=>i++);left=widget.list[i].seconds>0?widget.list[i].seconds:30;}else{timer?.cancel();setState(()=>running=false);showDone();}}else setState(()=>left--);});}void showDone()=>showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Workout Complete 🎉'),content:const Text('Great work! Your session has been completed.'),actions:[TextButton(onPressed:()=>Navigator.popUntil(context,(r)=>r.isFirst),child:const Text('DONE'))]));@override void dispose(){timer?.cancel();super.dispose();}@override Widget build(BuildContext c){final e=widget.list[i];return Scaffold(backgroundColor:dark,appBar:AppBar(backgroundColor:dark,foregroundColor:Colors.white,title:Text('${i+1}/${widget.list.length}')),body:Column(children:[Expanded(child:Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[ExercisePreview(exercise:e,size:230),const SizedBox(height:35),Text(e.name,style:const TextStyle(color:Colors.white,fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:20),Text(e.reps>0?'× ${e.reps}':'${left}s',style:const TextStyle(color:orange,fontSize:64,fontWeight:FontWeight.w900))])),LinearProgressIndicator(value:(i+1)/widget.list.length,minHeight:7,color:orange),Padding(padding:const EdgeInsets.all(20),child:Row(children:[Expanded(child:OutlinedButton(onPressed:()=>setState(()=>running=!running),child:Text(running?'PAUSE':'RESUME'))),const SizedBox(width:12),Expanded(child:FilledButton(onPressed:(){if(i<widget.list.length-1){setState(()=>i++);start();}},child:const Text('SKIP')))]))]));}}

class Profile extends StatelessWidget {const Profile({super.key});@override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[const CircleAvatar(radius:50,backgroundColor:orange,child:Text('P',style:TextStyle(color:Colors.white,fontSize:46,fontWeight:FontWeight.w900))),const SizedBox(height:12),const Center(child:Text('Pikachu Athlete',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900))),const SizedBox(height:25),_row(c,Icons.person,'Personal details'),_row(c,Icons.bar_chart,'Progress & history'),_row(c,Icons.settings,'Settings'),_row(c,Icons.help_outline,'Help & feedback')]));}
Widget _row(BuildContext c,IconData i,String t)=>Card(elevation:0,child:ListTile(leading:Icon(i,color:orange),title:Text(t),trailing:const Icon(Icons.chevron_right),onTap:()=>t=='Settings'?Navigator.push(c,MaterialPageRoute(builder:(_)=>const SettingsPage())):null));
class SettingsPage extends StatelessWidget {const SettingsPage({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Settings')),body:ListView(children:[SwitchListTile(value:true,onChanged:(_){},title:const Text('Workout reminders'),secondary:const Icon(Icons.notifications_outlined)),SwitchListTile(value:true,onChanged:(_){},title:const Text('Sound'),secondary:const Icon(Icons.volume_up_outlined)),SwitchListTile(value:true,onChanged:(_){},title:const Text('Vibration'),secondary:const Icon(Icons.vibration)),ListTile(title:const Text('Units'),subtitle:const Text('Metric (kg, cm)'),leading:const Icon(Icons.straighten)),const Divider(),ListTile(title:const Text('Supabase status'),subtitle:Text(supabaseUrl.isEmpty?'Not configured — add dart-define credentials':'Connected configuration detected'),leading:const Icon(Icons.cloud_done_outlined,color:orange))]));}
