import 'dart:async';
import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

const orange = Color(0xFFFF7A00);
const dark = Color(0xFF101114);
const supabaseUrl = String.fromEnvironment('SUPABASE_URL');
const supabaseKey = String.fromEnvironment('SUPABASE_ANON_KEY');

class PikachuWorkout extends StatelessWidget {
  const PikachuWorkout({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(debugShowCheckedModeBanner:false,title:'Pikachu Workout',theme:ThemeData(useMaterial3:true,colorSchemeSeed:orange),home:const AppGate());
}

class AppGate extends StatelessWidget {
  const AppGate({super.key});
  @override Widget build(BuildContext context) {
    if (supabaseUrl.isEmpty || supabaseKey.isEmpty) return const HomeShell();
    return StreamBuilder<AuthState>(stream:Supabase.instance.client.auth.onAuthStateChange,builder:(context,snap){
      return Supabase.instance.client.auth.currentSession == null ? const LoginPage() : const HomeShell();
    });
  }
}

class LoginPage extends StatefulWidget { const LoginPage({super.key}); @override State<LoginPage> createState()=>_LoginPageState(); }
class _LoginPageState extends State<LoginPage> {
  final email=TextEditingController(),password=TextEditingController(); bool signup=false,loading=false; String error='';
  Future<void> submit() async { setState(()=>loading=true); try { final a=Supabase.instance.client.auth; if(signup){await a.signUp(email:email.text.trim(),password:password.text);}else{await a.signInWithPassword(email:email.text.trim(),password:password.text);} } catch(e){if(mounted)setState(()=>error=e.toString());} finally{if(mounted)setState(()=>loading=false);} }
  @override Widget build(BuildContext c)=>Scaffold(backgroundColor:dark,body:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:Column(children:[const CircleAvatar(radius:58,backgroundColor:orange,child:Text('P',style:TextStyle(fontSize:58,fontWeight:FontWeight.w900,color:Colors.white))),const SizedBox(height:18),const Text('PIKACHU WORKOUT',style:TextStyle(color:Colors.white,fontSize:29,fontWeight:FontWeight.w900)),const SizedBox(height:28),TextField(controller:email,decoration:const InputDecoration(labelText:'Email',filled:true,fillColor:Colors.white,border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Password',filled:true,fillColor:Colors.white,border:OutlineInputBorder())),if(error.isNotEmpty)Padding(padding:const EdgeInsets.all(8),child:Text(error,style:const TextStyle(color:Colors.redAccent))),const SizedBox(height:12),SizedBox(width:double.infinity,height:54,child:FilledButton(onPressed:loading?null:submit,child:Text(loading?'PLEASE WAIT':signup?'CREATE ACCOUNT':'LOGIN'))),TextButton(onPressed:()=>setState(()=>signup=!signup),child:Text(signup?'Already have an account? Login':'New here? Create account',style:const TextStyle(color:Colors.white)))]))));
}

class Exercise { final String name,muscle; final int seconds,reps; const Exercise(this.name,this.muscle,{this.seconds=0,this.reps=0}); }
const exercises=<Exercise>[
 Exercise('Jumping Jacks','Full Body',seconds:20),Exercise('Abdominal Crunches','Abs',reps:16),Exercise('Russian Twist','Abs',reps:20),Exercise('Mountain Climbers','Core',seconds:30),Exercise('Push Ups','Chest',reps:12),Exercise('Bodyweight Squats','Legs',seconds:30),Exercise('Lunges','Legs & Glutes',seconds:24),Exercise('Plank','Core',seconds:30),Exercise('High Knees','Cardio',seconds:30),Exercise('Glute Bridge','Glutes',seconds:20),Exercise('Triceps Dips','Arms',reps:12),Exercise('Arm Circles','Shoulders',seconds:20),
];

class HomeShell extends StatefulWidget { const HomeShell({super.key}); @override State<HomeShell> createState()=>_HomeShellState(); }
class _HomeShellState extends State<HomeShell>{int tab=0;@override Widget build(BuildContext c){final pages=[const Dashboard(),const Workouts(),const Profile()];return Scaffold(body:pages[tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.fitness_center_outlined),selectedIcon:Icon(Icons.fitness_center),label:'Workouts'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Profile')]));}}

class Dashboard extends StatelessWidget { const Dashboard({super.key}); @override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[Row(children:[const CircleAvatar(radius:25,backgroundColor:orange,child:Text('P',style:TextStyle(color:Colors.white,fontSize:25,fontWeight:FontWeight.w900))),const SizedBox(width:12),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Good morning 👋',style:TextStyle(color:Colors.grey)),Text('Pikachu Athlete',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900))])),IconButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const SettingsPage())),icon:const Icon(Icons.settings_outlined))]),const SizedBox(height:18),Container(height:200,padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:dark,borderRadius:BorderRadius.circular(28)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('BE HEALTHY',style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),const Text('BE STRONGER',style:TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),const Text('BE YOURSELF',style:TextStyle(color:orange,fontSize:28,fontWeight:FontWeight.w900)),const Spacer(),FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const WorkoutDetail(title:'Full Body Workout'))),child:const Text('START WORKOUT →'))])),const SizedBox(height:20),Row(children:[_stat('🔥','7','Day streak'),_stat('⚡','420','Kcal'),_stat('⏱','35','Min')]),const SizedBox(height:22),const Text("Today's Workout",style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:8),_card(c,'Full Body Workout','35 min • 12 exercises','420 kcal'),const SizedBox(height:20),const Text('Quick Start',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),Wrap(spacing:8,children:['Abs','Chest','Legs','Arms','HIIT'].map((x)=>ActionChip(label:Text(x),onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>WorkoutDetail(title:'$x Workout'))))).toList())]));}
Widget _stat(String a,String b,String d)=>Expanded(child:Container(margin:const EdgeInsets.only(right:7),padding:const EdgeInsets.all(12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:Column(children:[Text(a),Text(b,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:20)),Text(d,style:const TextStyle(color:Colors.grey,fontSize:12))])));
Widget _card(BuildContext c,String t,String s,String k)=>Card(elevation:0,child:ListTile(contentPadding:const EdgeInsets.all(12),leading:const CircleAvatar(backgroundColor:orange,child:Icon(Icons.fitness_center,color:Colors.white)),title:Text(t,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('$s\n🔥 $k'),trailing:const Icon(Icons.arrow_forward_ios,size:16),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>WorkoutDetail(title:t))));
}

class Workouts extends StatelessWidget { const Workouts({super.key}); @override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[const Text('Workouts',style:TextStyle(fontSize:32,fontWeight:FontWeight.w900)),const Text('Train anywhere. No gym required.',style:TextStyle(color:Colors.grey)),const SizedBox(height:18),...['Full Body','Abs Beginner','Legs & Glutes','Chest & Arms','HIIT Cardio','Mobility & Stretch'].map((x)=>Card(elevation:0,child:ListTile(leading:const CircleAvatar(backgroundColor:orange,child:Icon(Icons.fitness_center,color:Colors.white)),title:Text(x,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(x=='Abs Beginner'?'16 min • 16 exercises':'30 min • 12 exercises'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>WorkoutDetail(title:x)))))])); }

class WorkoutDetail extends StatelessWidget { final String title; const WorkoutDetail({super.key,required this.title}); @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(title)),body:Column(children:[Container(width:double.infinity,margin:const EdgeInsets.all(14),padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:dark,borderRadius:BorderRadius.circular(28)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('LEVEL 1',style:TextStyle(color:orange,fontSize:28,fontWeight:FontWeight.w900)),SizedBox(height:25),Text('30 Minutes • 12 Exercises',style:TextStyle(color:Colors.white,fontSize:19,fontWeight:FontWeight.w700))])),Expanded(child:ListView.builder(itemCount:exercises.length,itemBuilder:(_,i){final e=exercises[i];return ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:18,vertical:5),leading:ExerciseAnimation(exercise:e,size:72),title:Text(e.name,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(e.seconds>0?'⏱ 00:${e.seconds.toString().padLeft(2,'0')}':'× ${e.reps}'),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>ExercisePage(exercise:e))));})),SafeArea(child:Padding(padding:const EdgeInsets.all(14),child(SizedBox(width:double.infinity,height:56,child:FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const WorkoutPlayer())),child:const Text('GO!',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900))))))])); }
}

class ExerciseAnimation extends StatefulWidget { final Exercise exercise; final double size; const ExerciseAnimation({super.key,required this.exercise,required this.size}); @override State<ExerciseAnimation> createState()=>_ExerciseAnimationState(); }
class _ExerciseAnimationState extends State<ExerciseAnimation> with SingleTickerProviderStateMixin {late AnimationController a;@override void initState(){super.initState();a=AnimationController(vsync:this,duration:const Duration(milliseconds:800))..repeat(reverse:true);}@override void dispose(){a.dispose();super.dispose();}@override Widget build(BuildContext c)=>AnimatedBuilder(animation:a,builder:(_,__)=>Container(width:widget.size,height:widget.size,decoration:BoxDecoration(color:dark,borderRadius:BorderRadius.circular(18)),child:Transform.translate(offset:Offset(0,-5*a.value),child:Icon(Icons.accessibility_new,color:orange,size:widget.size*.5))));}

class ExercisePage extends StatelessWidget { final Exercise exercise; const ExercisePage({super.key,required this.exercise}); @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(exercise.name.toUpperCase())),body:ListView(children:[Container(color:const Color(0xFF0A9F93),padding:const EdgeInsets.all(16),child:Column(children:[const Row(mainAxisAlignment:MainAxisAlignment.spaceEvenly,children:[Text('ANIMATION',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900)),Text('VIDEO',style:TextStyle(color:Colors.white70,fontWeight:FontWeight.w700))]),const SizedBox(height:18),ExerciseAnimation(exercise:exercise,size:300),const SizedBox(height:12),const Text('Animated exercise guide',style:TextStyle(color:Colors.white))])),_info('Introduction','Perform ${exercise.name} with controlled movement. Keep your core engaged and breathe steadily.'),_info('Muscle Focus',exercise.muscle),Padding(padding:const EdgeInsets.all(16),child:FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>WorkoutPlayer(single:exercise))),child:const Text('START EXERCISE')))]));}
Widget _info(String h,String t)=>Container(margin:const EdgeInsets.fromLTRB(10,10,10,0),padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(14)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(h,style:const TextStyle(fontSize:22,fontWeight:FontWeight.w800)),const SizedBox(height:10),Text(t,style:const TextStyle(fontSize:16,color:Colors.grey))]));
}

class WorkoutPlayer extends StatefulWidget { final Exercise? single; const WorkoutPlayer({super.key,this.single}); @override State<WorkoutPlayer> createState()=>_WorkoutPlayerState(); }
class _WorkoutPlayerState extends State<WorkoutPlayer>{late List<Exercise> list;int i=0,left=20;Timer? timer;bool running=true;@override void initState(){super.initState();list=widget.single==null?exercises:[widget.single!];start();}void start(){timer?.cancel();left=list[i].seconds>0?list[i].seconds:30;timer=Timer.periodic(const Duration(seconds:1),(_){if(!mounted||!running)return;if(left<=1){if(i<list.length-1){setState(()=>i++);left=list[i].seconds>0?list[i].seconds:30;}else{timer?.cancel();setState(()=>running=false);}}else setState(()=>left--);});}@override void dispose(){timer?.cancel();super.dispose();}@override Widget build(BuildContext c){final e=list[i];return Scaffold(backgroundColor:dark,appBar:AppBar(backgroundColor:dark,foregroundColor:Colors.white,title:Text('${i+1}/${list.length}')),body:Column(children:[Expanded(child:Center(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[ExerciseAnimation(exercise:e,size:240),const SizedBox(height:28),Text(e.name,style:const TextStyle(color:Colors.white,fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:15),Text(e.reps>0?'× ${e.reps}':'${left}s',style:const TextStyle(color:orange,fontSize:60,fontWeight:FontWeight.w900))])),LinearProgressIndicator(value:(i+1)/list.length,minHeight:7),Padding(padding:const EdgeInsets.all(20),child:Row(children:[Expanded(child:OutlinedButton(onPressed:()=>setState(()=>running=!running),child:Text(running?'PAUSE':'RESUME'))),const SizedBox(width:12),Expanded(child:FilledButton(onPressed:(){if(i<list.length-1){setState(()=>i++);start();}},child:const Text('SKIP')))]))]));}}

class Profile extends StatelessWidget { const Profile({super.key}); @override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(20),children:[const CircleAvatar(radius:50,backgroundColor:orange,child:Text('P',style:TextStyle(color:Colors.white,fontSize:46,fontWeight:FontWeight.w900))),const SizedBox(height:12),const Center(child:Text('Pikachu Athlete',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900))),const SizedBox(height:20),const ListTile(leading:Icon(Icons.local_fire_department,color:orange),title:Text('7 day streak'),trailing:Text('Active',style:TextStyle(fontWeight:FontWeight.w900))),const ListTile(leading:Icon(Icons.fitness_center,color:orange),title:Text('21 training sessions')),FilledButton.icon(onPressed:(){if(supabaseUrl.isNotEmpty)Supabase.instance.client.auth.signOut();},icon:const Icon(Icons.logout),label:const Text('LOG OUT')),OutlinedButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const SettingsPage())),icon:const Icon(Icons.settings),label:const Text('SETTINGS'))])); }
}
class SettingsPage extends StatefulWidget { const SettingsPage({super.key}); @override State<SettingsPage> createState()=>_SettingsPageState(); }
class _SettingsPageState extends State<SettingsPage>{bool sound=true,vibration=true,notifications=true;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Settings')),body:ListView(children:[SwitchListTile(title:const Text('Workout sound'),value:sound,onChanged:(v)=>setState(()=>sound=v)),SwitchListTile(title:const Text('Vibration'),value:vibration,onChanged:(v)=>setState(()=>vibration=v)),SwitchListTile(title:const Text('Notifications'),value:notifications,onChanged:(v)=>setState(()=>notifications=v)),const ListTile(title:Text('Units'),subtitle:Text('Metric (kg, cm)')),const ListTile(title:Text('Pikachu Workout'),subtitle:Text('Version 1.0.0'))]));}}
